---
name: Funciones y tipos de datos
locale: es
type: learning
beta: false
teacher_info: ''
language: javascript
id_format: "%05d"
order:
- 18
- 1
- 2
- 16
- 4
- 5
- 8
- 17
- 9
- 6
- 13
- 14
- 15
- 11
- 12
- 7
- 3
private: false
